services:
  blobcity:
    image: blobcity/db
    container_name: blobcity-db-container
    ports:
      - 10111:10111
      - 10113:10113
  cliente:
    image: soyangela/blobcity-db-client
    container_name: blob_client_container
    